### ISSUE TITLE
[suggestion] elfbot import <sonarr/radarr>

### ISSUE THREAD

**Issue by pomnz1982** [geek-cookbook/elf-charts#483]
using elfbot import sonarr/radarr which works similar to elfbot symlink here, but without the folders and sends the symlinks to /storage/symlinks/blackhole/<sonarr or radarr> for automatic import using a usenet blackhole (usenet so it doesnt conflict with rdtclient, we dont want it to try and send torrent requests to it instead of rdtclient), as long as the filenames are formatted correctly the usenet blackhole treats it as individual episode downloads so it doesnt matter if its multiple seasons mixed together, it will import them even if you send it symlinks from a multi-season torrent.

**Comment by funkypenguin** [comment]
Testing project workflow
