### ISSUE TITLE
Elfbot symlink here Premiumize mount incorrectly mounts the path!

### ISSUE THREAD

**Issue by diimaan** [geek-cookbook/elf-charts#487]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue)/[closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues exist for this bug

### 1️⃣ Description

When I run elfbot symlink here inside PM mount I get the following

elfbot symlink here

/storage/premiumize/anime-pm
Symlinking new items in /storage/premiumize to /storage/symlinks/import/premiumize... 
Done!

But at the same time if I run the following it works!
elfbot symlink /storage/premiumize/anime-pm/

Symlinking new items in /storage/premiumize/anime-pm/ to /storage/symlinks/import/anime-pm... 
Done!

### 2️⃣ Expected Behaviour

elfbot symlink here

/storage/premiumize/anime-pm
Symlinking new items in /storage/premiumize/anime-pm/ to /storage/symlinks/import/anime-pm...
Done!

### 3️⃣ Actual Behaviour

elfbot symlink here

/storage/premiumize/anime-pm
Symlinking new items in /storage/premiumize to /storage/symlinks/import/premiumize... 
Done!

### 4️⃣ Steps to Reproduce

1. Go into the PM mount folder.
2. Go into movies/shows/anime inside PM.
3. Run elfbot symlink here

### 5️⃣ Possible solutions

Instead of running elfbot symlink here run with elfbot and the actual mount path i.e. (elfbot symlink /storage/premiumize/anime-pm/)

### 💍 Engagement

- [X] Test the changes after a preview deploy and provide feedback
- [ ] Solicit community input in [Discord](http://chat.funkypenguin.co.nz)
- [ ] Submit a PR for a fix myself 🏆

### ✅ Code of Conduct

- [X] I agree to follow this Geek Cookbook's Code of Conduct

**Comment by funkypenguin** [comment]
Fixed, rolling out tonight!
